# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        packages:
            - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.9 # Unstable

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cd scripting/
    # - wget "https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc" -O include/updater.inc

    - chmod +x spcomp
script: ./compile.sh tutorial_text.sp freak_fortress_2/*.sp

# Notifications
notifications:
    email: false
