# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        packages:
            - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.9 # Unstable

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
script: ./compile.sh tutorial_text.sp tt_example.sp

# Notifications
notifications:
    email: false
